(define (problem move2_02)
   (:domain move2)
   (:objects rooma roomb roomc roomd)
   (:init (room rooma)
          (room roomb)
          (room roomc)
          (room roomd)
          (at-robby rooma)
          (next rooma roomb) (next roomb rooma)
          (next roomb roomc) (next roomc roomb)
          (next roomc roomd) (next roomd roomc)
          )
   (:goal (and
               (at-robby roomd))))