(define (problem move2_03)
   (:domain move2)
   (:objects rooma roomb roomc roomd roome)
   (:init (room rooma)
          (room roomb)
          (room roomc)
          (room roomd)
          (room roome)
          (at-robby rooma)
          (next rooma roomb) (next roomb rooma)
          (next roomb roomc) (next roomc roomb)
          (next roomc roomd) (next roomd roomc)
          (next roomd roome) (next roome roomd)
          )
   (:goal (and
               (at-robby roome))))