(define (problem strips-gripper-x-3)
   (:domain gripper-strips)
   (:objects rooma roomb roomc ball1 left)
   (:init (room rooma)
          (room roomb)
          (room roomc)
          (ball ball1)
          (gripper left)
          (at-robby rooma)
          (at ball1 rooma)
          (free left)
          )
   (:goal (and
               (at ball1 roomb)
               (at-robby roomc))))